version: '3.6'
services:
  app:
    tty: true
    stdin_open: true
    build: .
    command: rake spec
    volumes:
      - .:/app
    links:
      - redis
    environment:
      - SERVICE_PROTOCOL_TOKEN=123
  redis:
    image: redis:5.0.3-alpine
    expose:
      - '6379'